name: Node.js Package Publish

on:
  push:
    branches:
      - master

jobs:
  Run-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 9.x, 10.x, 12.x, 11.x, 14.x, latest]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - name: Use Node.js ${{ matrix.node-version }}
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm test

  publish-npm:
    needs: Run-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - run: npm ci
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
